name: Ubuntu CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev libdbus-1-dev pkg-config

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Test
        working-directory: src/ubuntu/AzPin
        run: cargo test

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build and Package
        working-directory: src/ubuntu/AzPin
        run: cargo deb

      - name: Rename DEB
        working-directory: src/ubuntu/AzPin
        run: |
          DEB_FILE=$(ls target/debian/*.deb | head -n 1)
          VERSION=$(grep '^version =' Cargo.toml | awk -F'"' '{print $2}')
          NEW_NAME="target/debian/AzPin-Ubuntu-x64-v${VERSION}.deb"
          mv "$DEB_FILE" "$NEW_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: azpin-ubuntu-amd64-deb
          path: src/ubuntu/AzPin/target/debian/AzPin-Ubuntu-x64-v*.deb

      # Snap disabled pending Snap Store manual review of first submission
      # - name: Inject Snap Version
      # - name: Build Snap
      # - name: Publish Snap


  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev libdbus-1-dev pkg-config

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Test
        working-directory: src/ubuntu/AzPin
        run: cargo test

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build and Package
        working-directory: src/ubuntu/AzPin
        run: cargo deb

      - name: Rename DEB
        working-directory: src/ubuntu/AzPin
        run: |
          DEB_FILE=$(ls target/debian/*.deb | head -n 1)
          VERSION=$(grep '^version =' Cargo.toml | awk -F'"' '{print $2}')
          NEW_NAME="target/debian/AzPin-Ubuntu-arm64-v${VERSION}.deb"
          mv "$DEB_FILE" "$NEW_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: azpin-ubuntu-arm64-deb
          path: src/ubuntu/AzPin/target/debian/AzPin-Ubuntu-arm64-v*.deb

      # Snap disabled pending Snap Store manual review of first submission
      # - name: Inject Snap Version
      # - name: Build Snap
      # - name: Publish Snap
