name: Ubuntu CI

on:
  workflow_dispatch:
  push:
    branches: [ feature/ubuntu-support ]

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev libdbus-1-dev pkg-config

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Test
        working-directory: src/ubuntu/AzPin
        run: cargo test



  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev libadwaita-1-dev libdbus-1-dev pkg-config

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Cargo Test
        working-directory: src/ubuntu/AzPin
        run: cargo test



